### ISSUE TITLE
Is there a limit to Deserialize packet size?

### ISSUE THREAD

**Issue by OpusK** [eProsima/micro-RTPS-agent#2]
Currently I have a topic that I'm having problems with.
This topic is the default message for ROS, [Odometry](http://docs.ros.org/kinetic/api/nav_msgs/html/msg/Odometry.html).

When this packet is published, UDP-based data is 760 bytes. (Checked by wire shark)
In this case, the following error occurs in the Agent.

```
deserialize eprosima::fastcdr::exception::NotEnoughMemoryException
Error processing WRITE_DATA submessage.
Error written data on DDS entity.
```
If I randomly send the Odometry with a reduced size to serialize, this error disappears.
This will clear the error, but as you know, this is not a normal topic.

Is the Agent limited to a certain size when processing input messages? If so, where should I fix it?

**Comment by julianbermudez** [comment]
Hi @OpusK,

You can change the transport MTU using the CMake flags: `-DCONFIG_TCP_TRANSPORT_MTU`, `-DCONFIG_UDP_TRANSPORT_MTU` and `-DCONFIG_SERIAL_TRANSPORT_MTU`. Please try to select a appropriate MTU and give me the feedback. Thanks.

**Comment by OpusK** [comment]
Hi, @julianbermudez, 

Thanks for your answer!
This issue has been resolved.
